#!/bin/sh

function isGitVersionGreaterThan2_23 {
    git version | cut -d ' ' -f3 > tmp
    echo 2.23 >> tmp
    local smaller_version=`sort -V < tmp | head -n 1`
    rm tmp
    if [ $smaller_version = "2.23" ]
    then
        true
    else
        false
    fi
}

function setTestOptionsFileContent {
    local options_file_path="$1"
    local backup_file_path="$options_file_path-backup"
    local content="$2"
    
    if test -f "$options_file_path"; then
        mv -f "$options_file_path" "$backup_file_path"
    fi

    echo "$content" > "$options_file_path"
}

function restoreOriginalOptionsFileContent {
    local options_file_path="$1"
    local backup_file_path="$options_file_path-backup"
    
    if test -f "$backup_file_path"; then
        mv -f "$backup_file_path" "$options_file_path"
    else
        rm "$options_file_path"
    fi
}

export -f isGitVersionGreaterThan2_23
export -f setTestOptionsFileContent
export -f restoreOriginalOptionsFileContent
