#!/bin/sh

function isGitVersionGreaterThan2_23 {
    git version | cut -d ' ' -f3 > tmp
    echo 2.23 >> tmp
    local smaller_version=`sort -V < tmp | head -n 1`
    rm tmp
    if [ $smaller_version = "2.23" ]
    then
        true
    else
        false
    fi
}

export -f isGitVersionGreaterThan2_23
