#!/bin/sh

# Usage: isGitVersionAtLeast 2.23
# Succeeds if the installed git version is greater than or equal to the given one.
function isGitVersionAtLeast {
    local required_version=$1
    local actual_version=`git version | cut -d ' ' -f3`
    local smaller_version=`printf '%s\n%s\n' "$actual_version" "$required_version" | sort -V | head -n 1`
    [ "$smaller_version" = "$required_version" ]
}

export -f isGitVersionAtLeast
