name: Unit tests

on:
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  integration_tests:
    name: Integration tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: |
          sh buildme.sh
          ln -s "$HOME/bin/s7" /usr/local/bin/s7
          git config --global pull.rebase false
          git config --global init.defaultBranch main
      - name: Test
        run: |
          cd system7-tests/integration
          sh test.sh --no-parallel
          exit $?
  
  xctests:
    name: XCTests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          xcodebuild -scheme system7-tests -configuration Release test | xcpretty
          exit ${PIPESTATUS[0]}
